language: smalltalk
sudo: false

os:
  - linux

smalltalk:
  - Pharo-6.1

# Unit tests run the normal pillar tests
# Integration tests test that pillar itself can interact with generated files, pdf generation, etc.
# System tests test that we can install and use pillar as a black box
env:
  matrix:
  - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf

install:
  # Pillar installation
  - git clone https://github.com/pillar-markup/pillar.git  # Clone pillar
  - cd pillar && ./scripts/build.sh && cd ..                              # Run pillar build script. Pillar will be built in `pwd`/build!
  - . pillar/scripts/ci/ensure_latex.sh                                   # Install latex
  - ./pillar/scripts/ci/ensure_book_dependencies.sh                       # Install latex dependencies required by pillar
  
script:
  - ./pillar/build/pillar build pdf

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-Magritte
  skip_cleanup: true
  user: ducasse
  key:
    secure: QbEDArB98C3Y38E76vb5xTzaH+EPVRSU9flNmIiOWNIL0OmFkGH+nm5WUN3wj2bo6jZWGYQlh2/z85/vPYNfqiQgoPaDJiaw/G9thb1u9EN3L1fc3PN7/fJzUs7GnTh/7hB4Z/MxWHkCfIlG9/wJRxZI7phUq1HJTrAUq4pahYTfu6krUOw0fatXjMywULpAIOJszrcPtgxA2JnCuFnNQaZQgLPNA6upd/vbAMa0KSqOQRzq5QmJWoP8hnHIRH4ZpkOxmvIVX/5WMwtsvLwqfma06NOkP3rlSi4YByHI2Y7Eb2y+sD3Enk6W/l2wRJvP8fwEbDK+7MAgvJpybmdD6eMhajrcSLFJFzge74OoWvJEgfgDgVCQg8uT5nNx1k3GzBLvTCQRyiRW3cd0pYW4IUUHoWwdxgzhI98eNtcQZQpAbEuF7WjZsL2tHnu6XiACNVeOYeu3YKygreHBiGmZ4QSAqwrq0r8JtREGPyItEyAZNxDK0PVwteTCxENY/YuEWQc+SkmduEN568u1uIIHJMklJql67oKoFeVbBquiGLpripctHsY3kyBXJap+z13Z7ESNqsJVJ+8ms6z73TKHM+ELl1DwsxLTkBL73XIdWXbetBApNuySobQ4DfH0LoXH5WBDCnGQtx1A2pufDp+HswPbu0qILI0R57Zhh45oRFo=
- provider: releases
  file: build/book.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
