sudo: required
services:
- docker

before_install:
- docker pull dpollet/texlive:pillar

script: |
  docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar bash -c "\
    wget --quiet --output-document=- 'https://raw.githubusercontent.com/pillar-markup/pillar/master/download.sh' | bash \
    && make book "

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-Magritte
  skip_cleanup: true
  user: ducasse
  key:
    secure:  IxgmjN1XNfWmK3GQDUYVJ6SxdoxCaAyhMQztfbQMCSDAuWzbrzuAY6WxKQ8Va5bCVqjGz1OpxKiEAN21Ye2lt56C97zBAeWeNr/Y3QXDWfYTuD0kP68kgtNzNGU8O102keTc00pz0s+YG8j3Ta2/A9Lbou/5WXYamOAsl1ogWd/FiB9IlqO5Ab6IoW7GPy/8cdWc/U4TlIIXuV0z/lX5as5KY6Ot51jWne+zlsf1kMZ4Obm2uI1bSZblbvRfkOdjYPTOjzhqPUEPBHmrxQqJOb104YrT3Gdaz6WwfeThlDlkK3JtxaC9N+jK7AnruZGios9JjxgZiIdFxwICo7D8ZdEEUvaLmzWOTBR1EqvwVEQrVG3pH6XaSeR2+gi7NZ5fYW9Vkpx+kNGeFRxvlAn/RNCz/O1Gf+K1L8dv2+2y36MBhgY7okoSZQOj9GB6Pax16shrxy/nLKuFJyf847kOo7VWQN8kUYjjQR/15KCUxrVMzp1OeW+jWn6k8fDe3jR4Pw+3kSo/KroSJwRPen04bl0QW4u113lytxlcTKRQL+MB5Br2DEuZefQgHe4FYWE6UIjHmJf2zV/V+m5CiIWW9Y4KVniPuh3FZEX2r5CuunmgwWR8XB8fQs5FdOaRKS1bZqJ86LGrqiBlt1590xdbnFfkX3mW1AS3ebyZH+koQDg=
- provider: releases
  file: build/smacc.spiral.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
